services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    env_file:
    - .env  # photologルートにある.envを指定
    tty: true          # コンテナを終了させずに維持する
    stdin_open: true   # 標準入力を開いたままにする
    volumes:
      # プロジェクト本体のマウント（VS Codeが自動で行う分を明示的に書く場合）
      - .:/workspaces/photolog:cached
      # 環境によって変わる実データフォルダのマウント
      # 指定がない場合はカレントディレクトリの dummy フォルダを指す
      - ${REAL_DATA_SOURCE:-./dummy}:/workspaces/photolog/local_processor/real-data:cached
    # devcontainer.json の runArgs や containerEnv の内容をこちらに移設可能
    environment:
      - TZ=Asia/Tokyo
    network_mode: bridge